
on: 
  push:
    branches: ["lab5"]
name: make changes
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: gl.umbc.edu
        username: ${{secrets.ftp_username}}
        password: ${{ secrets.ftp_password }}
        local_path: './*'
        remote_path: '/afs/umbc.edu/users/s/s/ss12/pub/www/lab5'
        sftp_only: true